/* pcl_config.h. Generated by CMake for PCL. */

/* PCL version string */
#define PCL_VERSION "1.3.0"

/* #undef HAVE_TBB */

#define HAVE_OPENNI 1

#define HAVE_QHULL 1

#define HAVE_QHULL_2011 1

/* #undef HAVE_CUDA */

#ifdef DISABLE_OPENNI
#undef HAVE_OPENNI
#endif

#ifdef DISABLE_QHULL
#undef HAVE_QHULL
#endif

